### ISSUE TITLE
Issues about the NYUD dataset

### ISSUE THREAD

**Issue by HarborYuan** [brdav/atrc#2]
Hi,

Thanks for your work on multi-task learning.

Currently, I am working on my own project with atrc, and I tried to use the multi-task baseline as a start. However, using the baselinemt.yml config file(bs 32 iter 80k), I only got 0.6755 RMSE Depth, 22.2 MAE Normal, 33.96 mIoU semseg, compared to 0.6248, 21.02, 36.35 in the paper. Smaller batch size and iterations lead to a worse result.

So, I want to ask that did I miss something or is there something I can do to build my own multi-task baseline in this codebase.

Best,
Harbor

**Comment by brdav** [comment]
Hello,
I reran that config and got 0.6323 RMSE Depth, 21.01 MEA Normals, 36.83 mIOU Semseg, which is consistent with the paper values (the values in the paper are averages of 5 runs with different random seeds). 
Did you try bs8 and 40k, as given in the config? Do all your software packages match the versions provided in the README?

**Comment by HarborYuan** [comment]
Thanks for your response.

I am new with pytorch-lightning and I used the latest version of pytorch-lightning previsouly. I reran it with the 1.1.8 version, and the results are consistent with the paper (0.625, 21.03, 36.13 for depth, normals, and semseg). Sorry for my question.
