### ISSUE TITLE
Potential bugs of the "relationalcontext" head

### ISSUE THREAD

**Issue by HarborYuan** [brdav/atrc#4]
Hi @brdav ,

It seems that the current version of relationalcontext head may have some potential bugs when handling t-label or s-label. It might need a bi-directional aux caculation.

https://github.com/brdav/atrc/blob/36a2f11b15f1e8630331506b7136a8299088506d/src/model/heads/relationalcontext.py#L157

might need to be changed to
```
for task in self.tasks:
        if any(self.atrc_genotype[task][source] == 3 for source in self.tasks):
            aux_tasks.append(task)
            continue
        if any(self.atrc_genotype[task][source] == 4 for source in self.tasks):
            aux_tasks.append(task)
            continue
        if any(self.atrc_genotype[target][task] == 3 for target in self.tasks):
            aux_tasks.append(task)
            continue
        if any(self.atrc_genotype[target][task] == 4 for target in self.tasks):
            aux_tasks.append(task)
            continue
```

Thanks

**Comment by HarborYuan** [comment]
And 

https://github.com/brdav/atrc/blob/36a2f11b15f1e8630331506b7136a8299088506d/src/model/heads/relationalcontext.py#L88

might need to be changed to:

```
                if self.atrc_genotype[t][s] == 1 or self.atrc_genotype[t][s] == 2:
                    cp_out.append(self.cp_blocks[t][s](target_task_feats=task_specific_feats[t],
                                                       source_task_feats=task_specific_feats[s]))
                else:
                    cp_out.append(self.cp_blocks[t][s](target_task_feats=task_specific_feats[t],
                                                       source_task_feats=task_specific_feats[s],
                                                       target_aux_prob=aux_prob[t],
                                                       source_aux_prob=aux_prob[s]))
```

Thanks again.

**Comment by brdav** [comment]
Hi,
thanks for pointing that out! After reviewing I think the function get_aux_tasks should be correct the way it is. The aux map for a task only needs to be computed if 1) it is a source task in S-label context or 2) it is a target task in T-label context.
However, the second correction you pointed out is definitely a bug, as in some cases indexing aux_prob will throw a key error, I missed that during code refactoring.
Reopen this if you disagree, in the meantime I will adapt the code.
Thanks,
David
