### ISSUE TITLE
Source task importance

### ISSUE THREAD

**Issue by 187185537** [brdav/atrc#7]
Hello, thank you very much for your outstanding contribution. I want to know how to generate the correlation visualization between different tasks in Figure 6 in this article..

**Comment by brdav** [comment]
Hi, I did not release the code for generating the source task importance. You can modify this code to save the CP block outputs on the disk for each test sample. To assess the importance of a specific source-target task connection, randomly shuffle the outputs of that connection and record the performance drop. Repeat this about 50 times for a given connection to get a good estimate.
